DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS MediaItems;
DROP TABLE IF EXISTS Tags;
DROP TABLE IF EXISTS Logs;

CREATE TABLE Users(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Username TEXT NOT NULL,
    PasswordHash TEXT NOT NULL,
    Email TEXT NOT NULL,
    Role TEXT NOT NULL,
    CreatedAt TEXT NOT NULL
);

CREATE TABLE MediaItems(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Title TEXT NOT NULL,
    Url TEXT NOT NULL,
    UserId INTEGER,
    CreatedAt TEXT NOT NULL,
    FOREIGN KEY(UserId) REFERENCES Users(Id)
);

CREATE TABLE Tags(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    MediaId INTEGER,
    FOREIGN KEY(MediaId) REFERENCES MediaItems(Id)
);

CREATE TABLE Logs(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Message TEXT NOT NULL,
    CreatedAt TEXT NOT NULL
);
